name: Go Unit Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.5"

      - name: Install dependencies
        run: go get .

      - name: Test with the Go CLI
        run: go test ./...
